# Generated by Django 3.1 on 2020-08-26 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200826_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsmeal',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 2, 37, 2, 427173)),
        ),
    ]
