# Generated by Django 3.1 on 2020-09-01 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200828_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 15, 33, 11, 596479)),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
