# Generated by Django 3.1 on 2020-09-06 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200906_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 16, 49, 48, 787979)),
        ),
    ]
