# Generated by Django 3.1 on 2020-09-07 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20200906_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsmeal',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 10, 57, 21, 866840)),
        ),
    ]
