# Generated by Django 3.1 on 2020-09-08 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200906_1648'),
        ('restaurants', '0008_auto_20200907_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 10, 59, 50, 388914)),
        ),
        migrations.RemoveField(
            model_name='restaurantsmeal',
            name='likes',
        ),
        migrations.AddField(
            model_name='restaurantsmeal',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='registration.MyUser'),
        ),
    ]
