# Generated by Django 3.1 on 2020-09-17 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20200908_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsmeal',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 31, 41, 311906)),
        ),
    ]
