# Generated by Django 3.1 on 2020-09-17 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_auto_20200917_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 35, 6, 453979)),
        ),
        migrations.AlterField(
            model_name='restaurantsmeal',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
