# Generated by Django 3.1 on 2020-09-17 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200906_1648'),
        ('restaurants', '0014_auto_20200917_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 36, 17, 956478)),
        ),
        migrations.AlterField(
            model_name='restaurantsmeal',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='registration.MyUser'),
        ),
    ]
