# Generated by Django 3.1 on 2020-09-17 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_auto_20200917_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsmeal',
            name='meal_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 44, 44, 506353)),
        ),
    ]
