# Generated by Django 3.1 on 2020-09-17 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_auto_20200917_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 2, 25, 6, 335325)),
        ),
    ]
