# Generated by Django 3.1 on 2020-09-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200906_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
